### ISSUE TITLE
Straighten namespace and pod name resolution logic

### ISSUE THREAD

**Issue by distol** [flant/addon-operator#47]
This issue is a follow-up for a fast fix introduced in #46 .

We shall do it in a proper way:
1. Remove [hardcoded namespace name](https://github.com/flant/addon-operator/blob/master/pkg/kube/kube.go#L16)
2. Don't use Hostname as a default for pod
3. Add two CLI args and use two existing env variables as defaults for them (ADDON_OPERATOR_NAMESPACE and ADDON_OPERATOR_POD)

**Comment by distol** [comment]
* `+` LISTEN_ADDRESS
* `+` LISTEN_PORT

**Comment by diafour** [comment]
Fixed by #48.

- `ADDON_OPERATOR_POD` is not needed anymore in `addon-operator`;
- `ADDON_OPERATOR_LISTEN_ADDRESS` is default to 0.0.0.0;
- `ADDON_OPERATOR_LISTEN_PORT` is default to 9650;
- `ADDON_OPERATOR_NAMESPACE` is now required and is not hardcoded. Examples use fieldRef in manifests to set this variable.

Documentation is added to RUNNING.md file.
